/**
 * Scraped motorcycle spare parts catalog from archive/bike.html (bikespareparts.pk snapshot).
 * Features genuine OEM bike parts for Honda CD70, CG125, Yamaha YBR, Suzuki GS150, and 70cc/125cc motorcycles.
 */

export const BIKE_SPARE_PARTS_SEED_PRODUCTS = [
  {
    name: 'Rear Shock Pump CD70 OEM Heavy Duty',
    brand: 'Atlas Honda OEM',
    category: 'Suspension',
    unit: 'pair',
    price: 750,
    compare_price: 900,
    cost_price: 520,
    stock: 45,
    sku: 'BSP-CD70-SHK-PMP',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/02/Rear-Shock-Pump-CD70-600x600.jpeg',
    description: 'Heavy duty OEM rear shock pump absorber pair for Honda CD70 & 70cc motorcycles. Chrome finish with high durability dampening.',
    domain_data: {
      bike_model: 'Honda CD70 / 70cc',
      part_type: 'Rear Shock Pump',
      origin: 'OEM Pakistan',
    },
    is_featured: true,
  },
  {
    name: 'CD70 Motorcycle Kick Starter – OEM Quality',
    brand: 'Atlas Honda OEM',
    category: 'Engine Parts',
    unit: 'pcs',
    price: 350,
    compare_price: 450,
    cost_price: 240,
    stock: 60,
    sku: 'BSP-CD70-KICK-STR',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/02/kick-starter-cd70-600x600.jpg',
    description: 'High-strength steel alloy kick starter lever arm for Honda CD70 and 70cc motorbikes. Rubber pedal grip included.',
    domain_data: {
      bike_model: 'Honda CD70 / China 70cc',
      part_type: 'Kick Starter',
      material: 'Forged Steel Alloy',
    },
    is_featured: true,
  },
  {
    name: 'Honda CG 125 Motorcycle Speedometer Assembly',
    brand: 'Atlas Honda OEM',
    category: 'Electrical & Meters',
    unit: 'pcs',
    price: 990,
    compare_price: 1200,
    cost_price: 680,
    stock: 25,
    sku: 'BSP-CG125-SPDMTR',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/02/speedo-meter-CG125-600x600.jpg',
    description: 'Complete analog speedometer gauge panel for Honda CG 125. Clear glass dial with RPM, fuel indicator, and wiring harness.',
    domain_data: {
      bike_model: 'Honda CG 125',
      part_type: 'Speedometer Unit',
      wiring_included: true,
    },
    is_featured: true,
  },
  {
    name: 'CG 125 Pressure Plate Set – 4 Pieces',
    brand: 'FCS Heavy Duty',
    category: 'Clutch & Transmission',
    unit: 'set',
    price: 400,
    compare_price: 520,
    cost_price: 280,
    stock: 50,
    sku: 'BSP-CG125-PRESS-PLT',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/01/CG-125-pressure-plate-set-600x600.jpeg',
    description: '4-piece high friction metal pressure plate set for Honda CG125 clutch housing assembly. Smooth gear shifting performance.',
    domain_data: {
      bike_model: 'Honda CG 125',
      part_type: 'Pressure Plate Set',
      pieces: '4 Pcs Set',
    },
  },
  {
    name: 'CG125 Clutch Plates Green – 5 Piece Set',
    brand: 'FCS Heavy Duty',
    category: 'Clutch & Transmission',
    unit: 'set',
    price: 900,
    compare_price: 1100,
    cost_price: 620,
    stock: 40,
    sku: 'BSP-CG125-CLTCH-PLT',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/01/CG125-clutch-plates-600x600.jpg',
    description: 'Premium Kevlar-friction green clutch plate 5-piece set for Honda CG125. Prevents clutch slipping under heavy load.',
    domain_data: {
      bike_model: 'Honda CG 125',
      part_type: 'Clutch Plates',
      material: 'Green Friction Fibre',
    },
    is_featured: true,
  },
  {
    name: 'Backlight Assembly CD70 – Crystal Clear Lens',
    brand: 'Crown OEM',
    category: 'Lights & Indicators',
    unit: 'pcs',
    price: 220,
    compare_price: 300,
    cost_price: 140,
    stock: 80,
    sku: 'BSP-CD70-TAIL-LGT',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/01/Backlight-CD70-600x600.jpg',
    description: 'High visibility rear backlight assembly with red brake lens, amber turn signals, and pre-fitted 12V bulb for Honda CD70.',
    domain_data: {
      bike_model: 'Honda CD70',
      part_type: 'Tail Light Assembly',
      voltage: '12V',
    },
  },
  {
    name: 'Fuel Tank Cap CD 70 with Keys Lock',
    brand: 'Atlas Honda OEM',
    category: 'Body & Tank',
    unit: 'pcs',
    price: 250,
    compare_price: 320,
    cost_price: 160,
    stock: 55,
    sku: 'BSP-CD70-TANK-CAP',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/01/Fuel-Tank-Cap-CD70-600x600.jpg',
    description: 'Leak-proof chrome plated fuel tank cap with dual security keys for Honda CD70 and 70cc motorcycles.',
    domain_data: {
      bike_model: 'Honda CD70 / 70cc',
      part_type: 'Fuel Tank Cap',
      includes_keys: true,
    },
  },
  {
    name: 'Honda CD70 Rear Wheel Hub Complete Assembly',
    brand: 'Crown OEM',
    category: 'Wheels & Brakes',
    unit: 'pcs',
    price: 1600,
    compare_price: 1850,
    cost_price: 1150,
    stock: 20,
    sku: 'BSP-CD70-REAR-HUB',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/01/Honda-CD70-Rear-Wheel-Hub-600x600.jpeg',
    description: 'Heavy duty alloy rear wheel drum hub complete with bearing seats and brake shoe drum housing for Honda CD70.',
    domain_data: {
      bike_model: 'Honda CD70',
      part_type: 'Rear Wheel Hub',
      material: 'Cast Aluminum Alloy',
    },
    is_featured: true,
  },
  {
    name: 'Premium Honda CD70 Front Shock Absorber Pair',
    brand: 'Atlas Honda OEM',
    category: 'Suspension',
    unit: 'pair',
    price: 3800,
    compare_price: 4200,
    cost_price: 2700,
    stock: 15,
    sku: 'BSP-CD70-FRNT-SHK',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/01/Honda-CD70-Front-Shock-600x600.jpg',
    description: 'Complete front hydraulic fork shock absorber assembly pair for Honda CD70. High comfort hydraulic oil dampening.',
    domain_data: {
      bike_model: 'Honda CD70',
      part_type: 'Front Shock Absorber Pair',
      type: 'Hydraulic Fork',
    },
    is_featured: true,
  },
  {
    name: 'CG125 Clutch Housing Outer Assembly Complete',
    brand: 'Crown OEM',
    category: 'Clutch & Transmission',
    unit: 'pcs',
    price: 3000,
    compare_price: 3400,
    cost_price: 2100,
    stock: 18,
    sku: 'BSP-CG125-CLT-HSG',
    image_url: 'https://bikespareparts.pk/wp-content/uploads/2026/01/clutch-housing-complete-CG125-600x600.jpg',
    description: 'Precision machined clutch primary gear outer housing assembly for Honda CG125. Heavy load gear teeth design.',
    domain_data: {
      bike_model: 'Honda CG 125',
      part_type: 'Clutch Outer Housing',
    },
    is_featured: true,
  },
];
