/**
 * Construction & Infrastructure Sector — Rich Seed Catalog (Pakistan 2026)
 * Used during registration for construction-contractor domain.
 * Materials: Grade 60 Rebar, OPC Cement, Bitumen, Aggregate, RMC, Sand, Labour, Equipment.
 */

export const CONSTRUCTION_CONTRACTOR_SEED_PRODUCTS = [
  // ── Civil & Structural Materials ─────────────────────────────────────────
  {
    name: 'Deformed Steel Rebar Grade 60 (12mm) — per Ton',
    brand: 'Mughal Steel',
    category: 'Civil & Structural',
    unit: 'Ton',
    sku: 'CONST-REBAR-12MM',
    price: 260000,
    compare_price: 275000,
    cost_price: 245000,
    stock: 120,
    min_stock_level: 20,
    reorder_point: 30,
    reorder_quantity: 50,
    description: 'ASTM A615 Grade 60 deformed steel reinforcement bars 12mm diameter. PEC/PPRA BOQ item for structural RCC work.',
    is_featured: true,
    is_new: false,
    domain_data: {
      boq_item_no: 'BOQ-3.1',
      specification_grade: 'ASTM A615 / BS 4449 Grade 60',
      schedule_code: 'MRS-PUNJAB-14.2',
      material_cost_ratio: '0.90',
      station_location: 'Central Batching Yard',
    },
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Deformed Steel Rebar Grade 60 (25mm) — per Ton',
    brand: 'Amreli Steels',
    category: 'Civil & Structural',
    unit: 'Ton',
    sku: 'CONST-REBAR-25MM',
    price: 265000,
    cost_price: 248000,
    stock: 80,
    min_stock_level: 15,
    reorder_point: 25,
    reorder_quantity: 40,
    description: 'ASTM A615 Grade 60 deformed steel rebar 25mm for heavy structural columns and piles.',
    domain_data: {
      boq_item_no: 'BOQ-3.2',
      specification_grade: 'ASTM A615 Grade 60',
      schedule_code: 'MRS-PUNJAB-14.2',
      material_cost_ratio: '0.90',
      station_location: 'Central Batching Yard',
    },
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Ordinary Portland Cement OPC 50kg Bag',
    brand: 'Bestway Cement',
    category: 'Civil & Structural',
    unit: 'Bag',
    sku: 'CONST-CEMENT-OPC-50KG',
    price: 1420,
    compare_price: 1480,
    cost_price: 1350,
    stock: 2500,
    min_stock_level: 400,
    reorder_point: 600,
    reorder_quantity: 1000,
    description: 'PSQCA certified OPC 50kg bag for concrete work, masonry, and plastering. Compliant with BS EN 197-1 CEM I 42.5N.',
    is_featured: true,
    domain_data: {
      boq_item_no: 'BOQ-3.5',
      specification_grade: 'PSQCA / BS EN 197-1 CEM I 42.5N',
      schedule_code: 'MRS-PUNJAB-6.1',
      material_cost_ratio: '0.95',
      station_location: 'Main Warehouse Shed',
    },
    image_url: 'https://images.unsplash.com/photo-1622397750700-c23e9060de0e?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Ready-Mix Concrete C25 (3000 PSI @ 28 Days) — per Cu.M',
    brand: 'RMC Plant',
    category: 'Civil & Structural',
    unit: 'Cu.M',
    sku: 'CONST-RMC-C25',
    price: 15500,
    cost_price: 14000,
    stock: 500,
    min_stock_level: 50,
    reorder_point: 100,
    reorder_quantity: 200,
    description: 'Grade C25 ready-mix concrete, 1:2:4 proportions, 28-day compressive strength 3000 PSI. For slabs, beams, and footings.',
    is_featured: true,
    domain_data: {
      boq_item_no: 'BOQ-3.6',
      specification_grade: 'Class B Concrete 1:2:4 Mix',
      schedule_code: 'MRS-PUNJAB-6.12',
      material_cost_ratio: '0.70',
      labor_cost_ratio: '0.20',
      station_location: 'Structure Pier P-01 to P-04',
    },
    image_url: 'https://images.unsplash.com/photo-1612537785038-1b17af20d5f7?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Ready-Mix Concrete C30 (4000 PSI @ 28 Days) — per Cu.M',
    brand: 'RMC Plant',
    category: 'Civil & Structural',
    unit: 'Cu.M',
    sku: 'CONST-RMC-C30',
    price: 17500,
    cost_price: 15800,
    stock: 300,
    min_stock_level: 30,
    reorder_point: 50,
    reorder_quantity: 150,
    description: 'Grade C30 high-strength ready-mix concrete for bridge piers, pile caps, and critical structural elements.',
    domain_data: {
      boq_item_no: 'BOQ-3.7',
      specification_grade: 'High Strength C30 @ 4000 PSI',
      schedule_code: 'MRS-PUNJAB-6.13',
      material_cost_ratio: '0.70',
      labor_cost_ratio: '0.20',
      station_location: 'Bridge Abutment Work',
    },
    image_url: 'https://images.unsplash.com/photo-1612537785038-1b17af20d5f7?w=800&q=82&auto=format&fit=crop',
  },

  // ── Roads & Asphalt Materials ─────────────────────────────────────────────
  {
    name: 'Bitumen Asphalt Binder Grade 60/70 — per Ton',
    brand: 'Attock Petroleum',
    category: 'Roads & Asphalt',
    unit: 'Ton',
    sku: 'CONST-BITUMEN-6070',
    price: 210000,
    compare_price: 220000,
    cost_price: 198000,
    stock: 80,
    min_stock_level: 10,
    reorder_point: 15,
    reorder_quantity: 30,
    description: 'Penetration Grade Bitumen 60/70 for dense-graded asphalt concrete pavement. AASHTO M20 compliant.',
    is_featured: true,
    domain_data: {
      boq_item_no: 'BOQ-4.2',
      specification_grade: 'AASHTO M20 Penetration 60/70',
      schedule_code: 'CSR-NHA-401B',
      material_cost_ratio: '0.85',
      station_location: 'Asphalt Plant Site Base',
    },
    image_url: 'https://images.unsplash.com/photo-1597000985042-5f12bd6af09f?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Crushed Stone Aggregate 19mm (Margalla) — per Cu.Ft',
    brand: 'Margalla Quarry',
    category: 'Roads & Asphalt',
    unit: 'Cu.Ft',
    sku: 'CONST-AGG-19MM',
    price: 120,
    cost_price: 95,
    stock: 15000,
    min_stock_level: 2000,
    reorder_point: 3000,
    reorder_quantity: 5000,
    description: 'Sub-base and aggregate base course Grade A, 19mm crushed stone from Margalla. AASHTO T27 grading.',
    domain_data: {
      boq_item_no: 'BOQ-4.1',
      specification_grade: 'Sub-base & Base Course Grade A',
      schedule_code: 'MRS-PUNJAB-4.3',
      material_cost_ratio: '0.80',
      station_location: 'KM 14+200 Stockpile Yard',
    },
    image_url: 'https://images.unsplash.com/photo-1580652868329-b3e94e9efad2?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'River Sand (Lawrencepur / Chenab) — per Cu.Ft',
    brand: 'Local Supplier',
    category: 'Roads & Asphalt',
    unit: 'Cu.Ft',
    sku: 'CONST-SAND-CU',
    price: 55,
    cost_price: 42,
    stock: 20000,
    min_stock_level: 2000,
    reorder_point: 4000,
    reorder_quantity: 8000,
    description: 'Well-graded river sand for concrete mixing, plastering, and backfill. FM 2.4–3.0.',
    domain_data: {
      boq_item_no: 'BOQ-4.3',
      specification_grade: 'FM 2.4-3.0 River Sand',
      schedule_code: 'MRS-PUNJAB-4.1',
      material_cost_ratio: '0.80',
      station_location: 'Material Stockpile Area',
    },
    image_url: 'https://images.unsplash.com/photo-1580652868329-b3e94e9efad2?w=800&q=82&auto=format&fit=crop',
  },

  // ── Earthwork & Compaction ────────────────────────────────────────────────
  {
    name: 'Earthwork Excavation & Sub-grade Compaction — per Cu.M',
    brand: 'Subcontractor',
    category: 'Earthwork & Compaction',
    unit: 'Cu.M',
    sku: 'CONST-EARTH-EXC',
    price: 600,
    cost_price: 480,
    stock: 25000,
    min_stock_level: 1000,
    description: 'Earthwork excavation, transport, and 95% Modified AASHTO Proctor compaction for road sub-grade and embankment.',
    is_featured: true,
    domain_data: {
      boq_item_no: 'BOQ-1.1',
      specification_grade: '95% Modified AASHTO Compaction',
      schedule_code: 'MRS-PUNJAB-3.1',
      machinery_cost_ratio: '0.60',
      labor_cost_ratio: '0.25',
      station_location: 'Embankment Reach-1',
    },
    image_url: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Disposal of Surplus Earth — per Cu.M (per Trip)',
    brand: 'Subcontractor',
    category: 'Earthwork & Compaction',
    unit: 'Trip',
    sku: 'CONST-EARTH-DISP',
    price: 2200,
    cost_price: 1800,
    stock: 5000,
    min_stock_level: 200,
    description: 'Disposal of surplus excavated earth by truck to designated tip-off area within 5km.',
    domain_data: {
      boq_item_no: 'BOQ-1.3',
      specification_grade: 'Truck Dumper 10m3 / 5km radius',
      schedule_code: 'MRS-PUNJAB-3.3',
      machinery_cost_ratio: '0.70',
      station_location: 'Designated Disposal Site',
    },
    image_url: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=82&auto=format&fit=crop',
  },

  // ── Plant & Heavy Equipment Logbook ───────────────────────────────────────
  {
    name: 'Excavator Hydraulic CAT 320 / PC200 — Hour Log',
    brand: 'Caterpillar',
    category: 'Plant & Heavy Equipment',
    unit: 'Hour',
    sku: 'CONST-EQ-EXC320',
    price: 14000,
    cost_price: 11000,
    stock: 2000,
    min_stock_level: 100,
    description: '1.0 Cu.M bucket capacity hydraulic excavator. Hour-meter log for site plant control, fuel tracking, and idle time analysis.',
    is_featured: true,
    domain_data: {
      boq_item_no: 'EQ-01',
      specification_grade: 'CAT 320 / PC200 1.0m3 Bucket Hydraulic Heavy Duty',
      schedule_code: 'CSR-MACH-01',
      machinery_cost_ratio: '0.90',
      station_location: 'Heavy Machinery Fleet Pool',
    },
    image_url: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Motor Grader CAT 140K — Hour Log',
    brand: 'Caterpillar',
    category: 'Plant & Heavy Equipment',
    unit: 'Hour',
    sku: 'CONST-EQ-MG140K',
    price: 16000,
    cost_price: 13000,
    stock: 1500,
    min_stock_level: 80,
    description: 'Motor grader for sub-grade shaping, shoulder grading, and aggregate spreading. Hour logbook with blade pass & fuel records.',
    domain_data: {
      boq_item_no: 'EQ-02',
      specification_grade: 'CAT 140K / 147kW Motor Grader',
      schedule_code: 'CSR-MACH-02',
      machinery_cost_ratio: '0.90',
      station_location: 'Road Grading Fleet',
    },
    image_url: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Vibratory Road Roller 10-12 Ton — Hour Log',
    brand: 'Dynapac',
    category: 'Plant & Heavy Equipment',
    unit: 'Hour',
    sku: 'CONST-EQ-ROLLER',
    price: 8500,
    cost_price: 7000,
    stock: 1200,
    min_stock_level: 60,
    description: '10-12 Ton vibratory smooth drum roller for compaction of asphalt layers and sub-base. Pass count log per section.',
    domain_data: {
      boq_item_no: 'EQ-03',
      specification_grade: '10-12 Ton Vibratory Steel Drum Roller',
      schedule_code: 'CSR-MACH-03',
      machinery_cost_ratio: '0.85',
      station_location: 'Compaction Fleet Pool',
    },
    image_url: 'https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Asphalt Paver Vögele Super 1900 — Hour Log',
    brand: 'Vögele',
    category: 'Plant & Heavy Equipment',
    unit: 'Hour',
    sku: 'CONST-EQ-PAVER',
    price: 30000,
    cost_price: 25000,
    stock: 800,
    min_stock_level: 50,
    description: 'Intelligent asphalt paver for base, binder, and wearing courses. Layer thickness, spread width, and tonnage logs.',
    is_featured: true,
    domain_data: {
      boq_item_no: 'EQ-04',
      specification_grade: 'Vögele Super 1900-3i / 8.5m Width Paver',
      schedule_code: 'CSR-MACH-04',
      machinery_cost_ratio: '0.90',
      station_location: 'Asphalt Paving Fleet',
    },
    image_url: 'https://images.unsplash.com/photo-1597000985042-5f12bd6af09f?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Concrete Transit Mixer Truck 6-8 Cu.M — Day Log',
    brand: 'Foton',
    category: 'Plant & Heavy Equipment',
    unit: 'Day',
    sku: 'CONST-EQ-MIXER',
    price: 95000,
    cost_price: 78000,
    stock: 400,
    min_stock_level: 20,
    description: '6-8 Cu.M drum transit mixer for RMC delivery. Drum revolution count, pour location, and delivery challan log.',
    domain_data: {
      boq_item_no: 'EQ-05',
      specification_grade: 'Foton 6-8m3 Drum Transit Mixer',
      schedule_code: 'CSR-MACH-05',
      machinery_cost_ratio: '0.85',
      station_location: 'Concrete Fleet Pool',
    },
    image_url: 'https://images.unsplash.com/photo-1612537785038-1b17af20d5f7?w=800&q=82&auto=format&fit=crop',
  },

  // ── Subcontractor Labour ──────────────────────────────────────────────────
  {
    name: 'Skilled Steel Fixer (Sariya Wala) — per Day',
    brand: 'Subcontractor',
    category: 'Subcontractor Labor',
    unit: 'Day',
    sku: 'CONST-LABOR-STEEL-FIXER',
    price: 3000,
    cost_price: 2500,
    stock: 500,
    min_stock_level: 50,
    description: 'Skilled reinforcement bar bender and fixer gang (Sariya Band). Daily labour log with BOQ item reference.',
    is_featured: true,
    domain_data: {
      boq_item_no: 'LAB-01',
      specification_grade: 'Skilled Structural Reinforcement Crew',
      schedule_code: 'MRS-LABOR-SKILLED',
      labor_cost_ratio: '0.95',
      station_location: 'Tower Slab Casting Deck',
    },
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Mason (Skilled Bricklayer / Raj Mistri) — per Day',
    brand: 'Subcontractor',
    category: 'Subcontractor Labor',
    unit: 'Day',
    sku: 'CONST-LABOR-MASON',
    price: 2800,
    cost_price: 2300,
    stock: 400,
    min_stock_level: 40,
    description: 'Skilled mason (Raj Mistri) for brick laying, block work, and plastering. Daily gang log with location.',
    domain_data: {
      boq_item_no: 'LAB-02',
      specification_grade: 'Skilled Mason / Raj Mistri',
      schedule_code: 'MRS-LABOR-MASON',
      labor_cost_ratio: '0.95',
      station_location: 'Block & Masonry Work',
    },
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'Unskilled Helper (Mazdoor) — per Day',
    brand: 'Subcontractor',
    category: 'Subcontractor Labor',
    unit: 'Day',
    sku: 'CONST-LABOR-HELPER',
    price: 1750,
    cost_price: 1400,
    stock: 800,
    min_stock_level: 80,
    description: 'General unskilled labourer (Mazdoor) for earthwork, material handling, and cleaning. Min wage compliance.',
    domain_data: {
      boq_item_no: 'LAB-03',
      specification_grade: 'Unskilled Helper / Mazdoor',
      schedule_code: 'MRS-LABOR-UNSKILLED',
      labor_cost_ratio: '0.98',
      station_location: 'General Site Labour Pool',
    },
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=82&auto=format&fit=crop',
  },

  // ── MEP & Electrical ─────────────────────────────────────────────────────
  {
    name: 'GI Water Supply Pipe 1" Class B (3m) — per R.Ft',
    brand: 'Popular Pipes',
    category: 'MEP & Electrical',
    unit: 'R.Ft',
    sku: 'CONST-MEP-GI-1IN',
    price: 320,
    cost_price: 265,
    stock: 3000,
    min_stock_level: 300,
    description: 'Galvanized iron water supply pipe 1" Class B, 3m lengths, for building water distribution.',
    domain_data: {
      boq_item_no: 'MEP-W-01',
      specification_grade: 'BS 1387 Class B GI Pipe 1"',
      schedule_code: 'MRS-PUNJAB-PLUMB-3.2',
      material_cost_ratio: '0.90',
      station_location: 'Building Water Riser Shaft',
    },
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=82&auto=format&fit=crop',
  },
  {
    name: 'XLPE Armoured Cable 4-Core 16mm² — per R.Ft',
    brand: 'PakCable',
    category: 'MEP & Electrical',
    unit: 'R.Ft',
    sku: 'CONST-MEP-XLPE-4C16',
    price: 1800,
    cost_price: 1550,
    stock: 2000,
    min_stock_level: 200,
    description: '4-core 16mm² XLPE SWA armoured cable for sub-main feeder circuits. IEC 60502-1 compliant.',
    domain_data: {
      boq_item_no: 'MEP-E-01',
      specification_grade: 'IEC 60502-1 XLPE 4C 16mm² SWA',
      schedule_code: 'MRS-PUNJAB-ELEC-5.1',
      material_cost_ratio: '0.88',
      station_location: 'Main Electrical Risers',
    },
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=82&auto=format&fit=crop',
  },
];
