/**
 * EV Bikes & Scooters seed catalog — inspired by Vlektra, Metro EV, and Ramza Aima models in Pakistan.
 * Includes complete technical specifications (battery, voltage, range, top speed, motor power, charging time).
 */

export const EV_BIKES_SEED_CATEGORIES = [
  'Electric Motorcycles',
  'Urban EV Scooters',
  'Long-Range Commuters',
  'High-Performance EV',
  'Batteries & Chargers',
  'Accessories & Spares',
];

export const EV_BIKES_SEED_PRODUCTS = [
  {
    name: 'Vlektra Retro (Café Racer EV Motorcycle)',
    brand: 'Vlektra',
    category: 'Electric Motorcycles',
    unit: 'unit',
    price: 579000,
    compare_price: 610000,
    cost_price: 480000,
    stock: 6,
    sku: 'EV-VLK-RETRO',
    image_url: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200&q=80&auto=format&fit=crop',
    is_featured: true,
    is_new: true,
    description: 'High-performance café racer style electric motorcycle with instant electric torque, 72V 32Ah Lithium-ion battery, CBS disc brakes, and futuristic digital cluster.',
    domain_data: {
      battery_type: 'Lithium-ion',
      battery_capacity: '72V 32Ah',
      voltage_v: '72V',
      motor_power_w: '1500W',
      range_km: 100,
      top_speed_kmh: 90,
      charging_time_hrs: '3.5 Hours',
      warranty_years: '3 Years',
    },
  },
  {
    name: 'Vlektra Velocity (Naked Sport EV)',
    brand: 'Vlektra',
    category: 'Electric Motorcycles',
    unit: 'unit',
    price: 419000,
    compare_price: 440000,
    cost_price: 345000,
    stock: 8,
    sku: 'EV-VLK-VELO',
    image_url: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1200&q=80&auto=format&fit=crop',
    is_featured: true,
    description: 'Aesthetic naked sport electric bike designed for urban performance, agile handling, 85 km range, and silent electric acceleration.',
    domain_data: {
      battery_type: 'Lithium-ion',
      battery_capacity: '72V 24Ah',
      voltage_v: '72V',
      motor_power_w: '1500W',
      range_km: 85,
      top_speed_kmh: 80,
      charging_time_hrs: '3 Hours',
      warranty_years: '3 Years',
    },
  },
  {
    name: 'Vlektra Rex (High-Performance Streetfighter EV)',
    brand: 'Vlektra',
    category: 'High-Performance EV',
    unit: 'unit',
    price: 669000,
    compare_price: 710000,
    cost_price: 550000,
    stock: 4,
    sku: 'EV-VLK-REX',
    image_url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=1200&q=80&auto=format&fit=crop',
    is_featured: true,
    is_new: true,
    description: 'Flagship streetfighter electric motorcycle featuring a 3000W motor, 120 km range, 110 km/h top speed, dual disc brakes, and smart app telemetry.',
    domain_data: {
      battery_type: 'Lithium-ion',
      battery_capacity: '72V 42Ah',
      voltage_v: '72V',
      motor_power_w: '3000W',
      range_km: 120,
      top_speed_kmh: 110,
      charging_time_hrs: '4 Hours',
      warranty_years: '3 Years',
    },
  },
  {
    name: 'Metro T9 Sport (Smart Urban EV Scooter)',
    brand: 'Metro EV',
    category: 'Urban EV Scooters',
    unit: 'unit',
    price: 184000,
    compare_price: 198000,
    cost_price: 148000,
    stock: 12,
    sku: 'EV-MTR-T9S',
    image_url: 'https://images.unsplash.com/photo-1571188654248-7a89213915f7?w=1200&q=80&auto=format&fit=crop',
    is_featured: true,
    description: 'Best-selling urban smart scooter with keyless start, anti-theft alarm, reverse gear, 90 km range, and long-life Graphene battery technology.',
    domain_data: {
      battery_type: 'Graphene',
      battery_capacity: '60V 32Ah',
      voltage_v: '60V',
      motor_power_w: '1200W',
      range_km: 90,
      top_speed_kmh: 55,
      charging_time_hrs: '5 Hours',
      warranty_years: '1.5 Years',
    },
  },
  {
    name: 'Metro Metrix NCF (Long-Range Smart Scooter)',
    brand: 'Metro EV',
    category: 'Long-Range Commuters',
    unit: 'unit',
    price: 250000,
    compare_price: 265000,
    cost_price: 202000,
    stock: 10,
    sku: 'EV-MTR-MTRX',
    image_url: 'https://images.unsplash.com/photo-1558980394-4c7c9299fe96?w=1200&q=80&auto=format&fit=crop',
    is_featured: true,
    description: 'Premium long-range electric scooter powered by a 1500W Bosch motor, 72V 32Ah Lithium battery, front & rear disc brakes, and 105 km range per charge.',
    domain_data: {
      battery_type: 'Lithium-ion',
      battery_capacity: '72V 32Ah',
      voltage_v: '72V',
      motor_power_w: '1500W',
      range_km: 105,
      top_speed_kmh: 65,
      charging_time_hrs: '3.5 Hours',
      warranty_years: '2 Years',
    },
  },
  {
    name: 'Metro E8S Pro (Heavy-Duty Commuter)',
    brand: 'Metro EV',
    category: 'Urban EV Scooters',
    unit: 'unit',
    price: 225000,
    compare_price: 240000,
    cost_price: 180000,
    stock: 7,
    sku: 'EV-MTR-E8SP',
    image_url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=1200&q=80&auto=format&fit=crop',
    description: 'Heavy-duty urban EV scooter with dual hydraulic suspension, LED headlight array, 100 km range, and reinforced chassis.',
    domain_data: {
      battery_type: 'Graphene',
      battery_capacity: '72V 32Ah',
      voltage_v: '72V',
      motor_power_w: '1200W',
      range_km: 100,
      top_speed_kmh: 60,
      charging_time_hrs: '4.5 Hours',
      warranty_years: '2 Years',
    },
  },
  {
    name: 'Ramza Liberty (Fashion Compact City Scooter)',
    brand: 'Ramza',
    category: 'Urban EV Scooters',
    unit: 'unit',
    price: 195000,
    compare_price: 210000,
    cost_price: 155000,
    stock: 9,
    sku: 'EV-RMZ-LBRT',
    image_url: 'https://images.unsplash.com/photo-1571188654248-7a89213915f7?w=1200&q=80&auto=format&fit=crop',
    is_featured: true,
    description: 'Fashion-forward compact city scooter powered by Ramza Aima Azure Controller for smooth torque delivery, 75 km range, and silent electric glide.',
    domain_data: {
      battery_type: 'Lithium-ion',
      battery_capacity: '60V 24Ah',
      voltage_v: '60V',
      motor_power_w: '1000W',
      range_km: 75,
      top_speed_kmh: 50,
      charging_time_hrs: '4 Hours',
      warranty_years: '2 Years',
    },
  },
  {
    name: 'Ramza Liberty Ultra (Enhanced Urban Performance)',
    brand: 'Ramza',
    category: 'Long-Range Commuters',
    unit: 'unit',
    price: 235000,
    compare_price: 250000,
    cost_price: 188000,
    stock: 6,
    sku: 'EV-RMZ-LULT',
    image_url: 'https://images.unsplash.com/photo-1558980394-4c7c9299fe96?w=1200&q=80&auto=format&fit=crop',
    description: 'Enhanced urban performance model featuring Golden Labeled Battery tech, 1500W motor, 95 km range, and dual hydraulic braking.',
    domain_data: {
      battery_type: 'Lithium-ion',
      battery_capacity: '72V 32Ah',
      voltage_v: '72V',
      motor_power_w: '1500W',
      range_km: 95,
      top_speed_kmh: 65,
      charging_time_hrs: '3.5 Hours',
      warranty_years: '2 Years',
    },
  },
  {
    name: 'Ramza Linbo (Sleek Commuter E-Bike)',
    brand: 'Ramza',
    category: 'Urban EV Scooters',
    unit: 'unit',
    price: 210000,
    compare_price: 225000,
    cost_price: 168000,
    stock: 11,
    sku: 'EV-RMZ-LNBO',
    image_url: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1200&q=80&auto=format&fit=crop',
    description: 'Sleek daily commuter scooter with comfortable seating, digital dash, 80 km range, and efficient silent engine.',
    domain_data: {
      battery_type: 'Graphene',
      battery_capacity: '60V 28Ah',
      voltage_v: '60V',
      motor_power_w: '1200W',
      range_km: 80,
      top_speed_kmh: 55,
      charging_time_hrs: '4 Hours',
      warranty_years: '1.5 Years',
    },
  },
  {
    name: 'Ramza Yaari Plus (Cargo & Utility EV Platform)',
    brand: 'Ramza',
    category: 'Long-Range Commuters',
    unit: 'unit',
    price: 245000,
    compare_price: 260000,
    cost_price: 195000,
    stock: 5,
    sku: 'EV-RMZ-YARI',
    image_url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=1200&q=80&auto=format&fit=crop',
    description: 'Robust utility platform with reinforced rear rack, 110 km range, heavy-duty battery pack, and high load capacity.',
    domain_data: {
      battery_type: 'Graphene',
      battery_capacity: '72V 38Ah',
      voltage_v: '72V',
      motor_power_w: '1500W',
      range_km: 110,
      top_speed_kmh: 50,
      charging_time_hrs: '5 Hours',
      warranty_years: '2 Years',
    },
  },
  {
    name: 'Tenvo EV Smart Fast Charger (72V 10A)',
    brand: 'Tenvo EV',
    category: 'Batteries & Chargers',
    unit: 'pcs',
    price: 18500,
    compare_price: 21000,
    cost_price: 12500,
    stock: 25,
    sku: 'EV-ACC-CHG72V',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80&auto=format&fit=crop',
    description: 'Smart pulse fast charger with auto-cutoff, thermal overload protection, and dual LED charging status indicator.',
    domain_data: {
      voltage_v: '72V',
      charging_time_hrs: '2-3 Hours',
      warranty_years: '1 Year',
    },
  },
  {
    name: 'Tenvo High-Density Lithium Battery Pack (72V 32Ah)',
    brand: 'Tenvo EV',
    category: 'Batteries & Chargers',
    unit: 'unit',
    price: 145000,
    compare_price: 160000,
    cost_price: 112000,
    stock: 14,
    sku: 'EV-BAT-72V32AH',
    image_url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1200&q=80&auto=format&fit=crop',
    description: 'High-density grade-A Lithium-ion battery pack with smart BMS protection, 2000+ charge cycles, and aluminum casing.',
    domain_data: {
      battery_type: 'Lithium-ion',
      battery_capacity: '72V 32Ah',
      voltage_v: '72V',
      warranty_years: '2 Years',
    },
  },
];
