/**
 * Rich seed products for boutique / textile demos, names, PKR pricing, and
 * domain_data aligned with Limelight & Khaadi navigation (Unstitched, RTW,
 * Accessories, New In). Images from fashionDemoImages.js (Unsplash).
 */
import { fashionStockImage, FASHION_DEMO_IMAGES } from './fashionDemoImages.js';

const U = FASHION_DEMO_IMAGES.unstitched;
const R = FASHION_DEMO_IMAGES.rtw;
const A = FASHION_DEMO_IMAGES.accessories;
const W = FASHION_DEMO_IMAGES.western;

/** @type {Array<Record<string, unknown>>} */
export const BOUTIQUE_FASHION_SEED_PRODUCTS = [
  // ── Unstitched ────────────────────────────────────────────────────────────
  {
    name: '3 Piece Lawn Suit (Unstitched)',
    brand: 'Limelight',
    category: 'Unstitched Fabric',
    unit: 'set',
    price: 4699,
    compare_price: 5200,
    cost_price: 3200,
    stock: 48,
    sku: 'LL-LWN-3PC-001',
    description: 'Signature summer lawn, shirt, dupatta & trouser fabric.',
    image_url: fashionStockImage(U.summer),
    domain_data: {
      fabrictype: 'Lawn',
      stitchingtype: 'Unstitched',
      korafinished: 'Printed',
      collection: 'Summer',
      designer: 'Limelight',
      season: 'Summer',
      sourcing: 'local',
    },
    is_featured: true,
    is_new: true,
  },
  {
    name: '3 Piece Lawn Suit, Embroidered (Unstitched)',
    brand: 'Khaadi',
    category: 'Unstitched Fabric',
    unit: 'set',
    price: 5999,
    compare_price: 6500,
    cost_price: 4100,
    stock: 36,
    sku: 'KH-LWN-EMB-002',
    description: 'Embroidered lawn 3pc, festive unstitched collection.',
    image_url: fashionStockImage(U.embroidered),
    domain_data: {
      fabrictype: 'Lawn',
      stitchingtype: 'Unstitched',
      korafinished: 'Embroidered',
      collection: 'Festive',
      designer: 'Khaadi',
      season: 'Eid',
      sourcing: 'local',
    },
    is_new: true,
  },
  {
    name: 'Chiffon Embroidered 3 Piece (Unstitched)',
    brand: 'Sana Safinaz',
    category: 'Unstitched Fabric',
    unit: 'set',
    price: 12500,
    compare_price: 14900,
    cost_price: 9200,
    stock: 18,
    sku: 'SS-CHF-UNS-003',
    description: 'Luxury chiffon with organza dupatta, unstitched formal.',
    image_url: fashionStockImage(U.chiffon || U.embroidered),
    domain_data: {
      fabrictype: 'Chiffon',
      stitchingtype: 'Unstitched',
      korafinished: 'Embroidered',
      collection: 'Formal',
      designer: 'Sana Safinaz',
      season: 'Wedding',
      sourcing: 'local',
    },
    is_featured: true,
  },

  // ── Luxury Pret (Ready-to-Wear) ───────────────────────────────────────────
  {
    name: '2 Piece Embroidered Cambric Pret',
    brand: 'Maria B',
    category: 'Luxury Pret',
    unit: 'set',
    price: 8900,
    compare_price: 9999,
    cost_price: 6200,
    stock: 22,
    sku: 'MB-RTW-EMB-004',
    description: 'Ready-to-wear embroidered cambric pret suit.',
    image_url: fashionStockImage(R.embroidered),
    domain_data: {
      fabrictype: 'Cambric',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Embroidered',
      collection: 'Luxury Pret',
      designer: 'Maria B',
      season: 'Eid',
      sourcing: 'local',
      articleno: 'MB-LP-204',
    },
    is_new: true,
    is_featured: true,
  },
  {
    name: 'Silk Pret 2 Piece',
    brand: 'Zara Shahjahan',
    category: 'Luxury Pret',
    unit: 'set',
    price: 9990,
    compare_price: 11500,
    cost_price: 7200,
    stock: 12,
    sku: 'ZS-SLK-PRT-005',
    description: 'Silk pret shirt & trouser, signature collection.',
    image_url: fashionStockImage(R.silk),
    domain_data: {
      fabrictype: 'Silk',
      stitchingtype: 'Ready-to-Wear',
      collection: 'Signature',
      designer: 'Zara Shahjahan',
      season: 'Wedding',
      sourcing: 'local',
    },
  },
  {
    name: 'Longline Lawn Kurta (Pret)',
    brand: 'Khaadi',
    category: 'Luxury Pret',
    unit: 'pcs',
    price: 4990,
    compare_price: 5490,
    cost_price: 3400,
    stock: 28,
    sku: 'KH-RTW-KRT-006',
    description: 'Embroidered lawn longline kurta, ready to wear.',
    image_url: fashionStockImage(R.kurtis),
    domain_data: {
      fabrictype: 'Lawn',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Embroidered',
      collection: 'Luxury Pret',
      designer: 'Khaadi',
      season: 'Summer',
      sourcing: 'local',
    },
    is_featured: true,
  },

  // ── Bridal ────────────────────────────────────────────────────────────────
  {
    name: 'Bridal Lehenga — Embroidered Velvet',
    brand: 'HSY',
    category: 'Bridal',
    unit: 'set',
    price: 85000,
    compare_price: 95000,
    cost_price: 62000,
    stock: 4,
    sku: 'HSY-BRD-VLV-007',
    description: 'Embroidered velvet bridal lehenga choli with dupatta. Bespoke stitching included.',
    image_url: fashionStockImage(U.embroidered),
    domain_data: {
      fabrictype: 'Velvet',
      stitchingtype: 'Boutique Stitched',
      collection: 'Bridal',
      designer: 'HSY',
      season: 'Wedding',
      sourcing: 'local',
      articleno: 'HSY-BR-007',
    },
    is_featured: true,
  },
  {
    name: 'Bridal Organza Gharara Set',
    brand: 'Sana Safinaz',
    category: 'Bridal',
    unit: 'set',
    price: 45000,
    compare_price: 52000,
    cost_price: 32000,
    stock: 6,
    sku: 'SS-BRD-ORG-008',
    description: 'Heavily embroidered organza gharara bridal set with dupatta.',
    image_url: fashionStockImage(U.chiffon || U.embroidered),
    domain_data: {
      fabrictype: 'Organza',
      stitchingtype: 'Boutique Stitched',
      collection: 'Bridal',
      designer: 'Sana Safinaz',
      season: 'Wedding',
      sourcing: 'local',
      articleno: 'SS-BR-008',
    },
    is_featured: true,
  },

  // ── Semi-Formal / Wedding Wear ────────────────────────────────────────────
  {
    name: 'Formal Embroidered Kurta (Pret)',
    brand: 'Faraz Manan',
    category: 'Semi-Formal',
    unit: 'pcs',
    price: 7500,
    cost_price: 5200,
    stock: 20,
    sku: 'FM-RTW-FRM-009',
    description: 'Party formal embroidered kurta.',
    image_url: fashionStockImage(R.formals),
    domain_data: {
      fabrictype: 'Organza',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Embroidered',
      collection: 'Formal',
      designer: 'Faraz Manan',
      season: 'Wedding',
      sourcing: 'local',
    },
  },
  {
    name: 'Luxury Pret Co-ord Set — Imported',
    brand: 'Elan',
    category: 'Casual',
    unit: 'set',
    price: 8900,
    compare_price: 10500,
    cost_price: 6500,
    stock: 14,
    sku: 'EL-COORD-010',
    description: 'Imported fabric co-ord set, shirt & trouser.',
    image_url: fashionStockImage(R.coords),
    domain_data: {
      fabrictype: 'Viscose',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Printed',
      collection: 'Casual',
      designer: 'Elan',
      season: 'Summer',
      sourcing: 'imported',
      origin: 'Turkey',
    },
    is_featured: true,
  },

  // ── Casual ────────────────────────────────────────────────────────────────
  {
    name: 'Solid Cambric Kurta (Pret)',
    brand: 'Limelight',
    category: 'Casual',
    unit: 'pcs',
    price: 3490,
    cost_price: 2400,
    stock: 35,
    sku: 'LL-RTW-SLD-011',
    description: 'Monochrome solids pret kurta.',
    image_url: fashionStockImage(R.solids),
    domain_data: {
      fabrictype: 'Cambric',
      stitchingtype: 'Ready-to-Wear',
      korafinished: 'Dyed',
      collection: 'Casual',
      designer: 'Limelight',
      season: 'Spring',
      sourcing: 'local',
    },
  },

  // ── Accessories ───────────────────────────────────────────────────────────
  {
    name: 'Viscose Scarf',
    brand: 'Limelight',
    category: 'Accessories',
    unit: 'pcs',
    price: 1199,
    compare_price: 1399,
    cost_price: 650,
    stock: 80,
    sku: 'LL-ACC-SCF-012',
    description: 'Lightweight viscose scarf.',
    image_url: fashionStockImage(A.scarf),
    domain_data: {
      accessoryType: 'Scarves',
      collection: 'Accessories',
      sourcing: 'local',
    },
    is_new: true,
  },
  {
    name: 'Embroidered Organza Dupatta',
    brand: 'Nomi Ansari',
    category: 'Accessories',
    unit: 'pcs',
    price: 3490,
    cost_price: 2200,
    stock: 30,
    sku: 'NA-ACC-DUP-013',
    description: 'Organza embroidered dupatta.',
    image_url: fashionStockImage(A.dupattas),
    domain_data: {
      fabrictype: 'Organza',
      accessoryType: 'Dupattas',
      collection: 'Accessories',
      designer: 'Nomi Ansari',
      sourcing: 'local',
    },
  },
  {
    name: 'Structured Crossbody Bag — Imported',
    brand: 'Imported',
    category: 'Accessories',
    unit: 'pcs',
    price: 3490,
    compare_price: 4290,
    cost_price: 2100,
    stock: 18,
    sku: 'LL-ACC-BAG-014',
    description: 'Crossbody handbag with chain detail, imported.',
    image_url: fashionStockImage(A.bag),
    domain_data: {
      accessoryType: 'Bags',
      collection: 'Accessories',
      sourcing: 'imported',
      origin: 'Turkey',
    },
    is_new: true,
  },
];

/** Categories seeded for boutique-fashion registration (matches setupTemplate.categories). */
export const BOUTIQUE_FASHION_SEED_CATEGORIES = [
  'Bridal',
  'Luxury Pret',
  'Semi-Formal',
  'Casual',
  'Wedding Wear',
  'Accessories',
  'Unstitched Fabric',
];
