/**
 * Hardware & Architectural Fittings Demo Seed Product Catalog.
 * Curated from scraped Pakistani hardware resources (Anwer Hardware, Building Hardware PK, Martell Hardware, VHID Doors).
 * Safe demo imagery via Unsplash & domain fallback pools.
 */

import { buildUnsplashImageUrl } from '../../storefront/unsplashUrl.js';

function stockImage(photoId) {
  return buildUnsplashImageUrl(photoId, { width: 800, quality: 80 });
}

export const HARDWARE_SEED_PRODUCTS = Object.freeze([
  {
    name: 'DTC C85B Hinge 3D Hydraulic (Soft-Close Half-Overlay)',
    brand: 'DTC',
    category: 'Hydraulic Hinges & Soft Close',
    unit: 'pcs',
    price: 480,
    compare_price: 550,
    cost_price: 310,
    stock: 350,
    sku: 'DTC-C85B-HO',
    description: '3D adjustable hydraulic soft-close concealed hinge for kitchen cabinet doors. Nickel plated steel with clip-on mounting plate.',
    image_url: stockImage('1581092160562-40aa08e78837'),
    domain_data: {
      itemcode: '100606169',
      material: 'Cold Rolled Steel',
      finish: 'Satin Nickel (SN)',
      size: '35mm Cup (Half-Overlay)',
      pcsperbox: 25,
      warranty: '5 Years Mechanism',
    },
    is_featured: true,
  },
  {
    name: 'DTC C85 Hinge 3D Hydraulic (Full Overlay)',
    brand: 'DTC',
    category: 'Hydraulic Hinges & Soft Close',
    unit: 'pcs',
    price: 520,
    compare_price: 600,
    cost_price: 340,
    stock: 280,
    sku: 'DTC-C85-FO',
    description: 'Heavy duty 3D hydraulic soft-close hinge full overlay with integrated damper.',
    image_url: stockImage('1581092160562-40aa08e78837'),
    domain_data: {
      itemcode: '100606168',
      material: 'Cold Rolled Steel',
      finish: 'Satin Nickel (SN)',
      size: '35mm Cup (Full Overlay)',
      pcsperbox: 25,
      warranty: '5 Years Mechanism',
    },
  },
  {
    name: 'DTC Tandembox Double Gallery Round Grey (18" / 450mm)',
    brand: 'DTC',
    category: 'Drawer Slides & Systems',
    unit: 'set',
    price: 14500,
    compare_price: 16800,
    cost_price: 10200,
    stock: 24,
    sku: 'DTC-TB-450-GRY',
    description: 'Double round gallery soft-close tandembox drawer system with full extension synchronized runners.',
    image_url: stockImage('1556911220-e15b29be8c8f'),
    domain_data: {
      itemcode: '100406175',
      material: 'Steel & Aluminum',
      finish: 'Dark Anthracite / Smoked',
      size: '450mm (18")',
      pcsperbox: 1,
      warranty: '5 Years Mechanism',
    },
    is_featured: true,
  },
  {
    name: 'DTC HKXS Single Lift-Up Mechanism (SE00AH01)',
    brand: 'DTC',
    category: 'Cabinet Fittings & Lift-Ups',
    unit: 'set',
    price: 8900,
    compare_price: 9800,
    cost_price: 6400,
    stock: 18,
    sku: 'DTC-HKXS-SE00',
    description: 'Compact lift-up mechanism for overhead wall cabinets with soft-close stay.',
    image_url: stockImage('1556911220-e15b29be8c8f'),
    domain_data: {
      itemcode: '100306178',
      material: 'Zinc Alloy (Zamac)',
      finish: 'SS Satin / Brushed',
      size: 'Standard Overhead',
      pcsperbox: 1,
      warranty: '3 Years Mechanism',
    },
  },
  {
    name: 'DTC HF Double Liftup Mechanism (ST04AM02B)',
    brand: 'DTC',
    category: 'Cabinet Fittings & Lift-Ups',
    unit: 'set',
    price: 18500,
    compare_price: 21000,
    cost_price: 13200,
    stock: 15,
    sku: 'DTC-HF-ST04',
    description: 'Bi-fold double door liftup flap system for tall kitchen wall cabinets with multi-stop positioning.',
    image_url: stockImage('1556911220-e15b29be8c8f'),
    domain_data: {
      itemcode: '100306177',
      material: 'Steel & Zinc Alloy',
      finish: 'Dark Anthracite / Smoked',
      size: 'Bi-Fold High Cabinet',
      pcsperbox: 1,
      warranty: '5 Years Mechanism',
    },
  },
  {
    name: 'Roeasy Concealed Levitating Air Hinge (Dark Finish)',
    brand: 'Roeasy',
    category: 'Hydraulic Hinges & Soft Close',
    unit: 'set',
    price: 16500,
    compare_price: 18900,
    cost_price: 11800,
    stock: 12,
    sku: 'ROE-AIR-DARK',
    description: 'Premium concealed levitating air hinge set supporting up to 7ft large wardrobe & aluminum frame doors.',
    image_url: stockImage('1581092160562-40aa08e78837'),
    domain_data: {
      itemcode: '100605431',
      material: 'Zinc Alloy (Zamac)',
      finish: 'Dark Anthracite / Smoked',
      size: 'Supports 7ft Door',
      pcsperbox: 1,
      warranty: '10 Years Finish Guarantee',
    },
    is_featured: true,
  },
  {
    name: 'Roeasy Automatic Push Door Opener with Soft Close',
    brand: 'Roeasy',
    category: 'Cabinet Fittings & Lift-Ups',
    unit: 'set',
    price: 9800,
    compare_price: 11500,
    cost_price: 6900,
    stock: 20,
    sku: 'ROE-AUTO-PUSH',
    description: 'Full opening automatic push system for large kitchen wardrobe doors with integrated soft-close damping.',
    image_url: stockImage('1556911220-e15b29be8c8f'),
    domain_data: {
      itemcode: '100605428',
      material: 'ABS Plastic & Aluminum',
      finish: 'Matt Black (MB)',
      size: 'Universal Push System',
      pcsperbox: 1,
      warranty: '3 Years Mechanism',
    },
  },
  {
    name: 'Blum Legrabox Designer Box Drawer (Noble Rust, 4")',
    brand: 'Blum',
    category: 'Drawer Slides & Systems',
    unit: 'set',
    price: 38000,
    compare_price: 42500,
    cost_price: 27500,
    stock: 8,
    sku: 'BLM-LEG-RUST-4',
    description: 'Special edition designer box drawer system by Blum in Noble Rust finish with ultra-smooth Blumotion damping.',
    image_url: stockImage('1556911220-e15b29be8c8f'),
    domain_data: {
      itemcode: '100406093',
      material: 'Stainless Steel SS 304',
      finish: 'PVD Gold',
      size: '4-Inch Side Height',
      pcsperbox: 1,
      warranty: 'Lifetime Warranty',
    },
    is_featured: true,
  },
  {
    name: 'Philips 720MVP Palm Vein Smart Digital Lock',
    brand: 'Philips',
    category: 'Digital & Smart Locks',
    unit: 'set',
    price: 145000,
    compare_price: 165000,
    cost_price: 105000,
    stock: 6,
    sku: 'PHL-720MVP-BLK',
    description: 'Flagship smart door lock with palm vein recognition, 3D facial unlock, HD camera video intercom, & C-grade lock cylinder.',
    image_url: stockImage('1558002038-1055907df827'),
    domain_data: {
      itemcode: '10106068',
      material: 'Aluminum Alloy & Tempered Glass',
      finish: 'Matt Black (MB)',
      size: 'Universal Mortise 6085',
      pcsperbox: 1,
      warranty: '3 Years Mechanism',
    },
    is_featured: true,
  },
  {
    name: 'Philips 608E Biometric Smart Lever Lock',
    brand: 'Philips',
    category: 'Digital & Smart Locks',
    unit: 'set',
    price: 85000,
    compare_price: 95000,
    cost_price: 61000,
    stock: 10,
    sku: 'PHL-608E-SLV',
    description: 'Biometric smart lever door lock 6000 series with fingerprint sensor on handle, PIN, & RFID keycard.',
    image_url: stockImage('1558002038-1055907df827'),
    domain_data: {
      itemcode: '10006070',
      material: 'Zinc Alloy (Zamac)',
      finish: 'Satin Nickel (SN)',
      size: 'Standard Mortise',
      pcsperbox: 1,
      warranty: '3 Years Mechanism',
    },
  },
  {
    name: 'Philips 240X Smart Deadbolt Lock (4000 Series)',
    brand: 'Philips',
    category: 'Digital & Smart Locks',
    unit: 'set',
    price: 48000,
    compare_price: 54000,
    cost_price: 34000,
    stock: 14,
    sku: 'PHL-240X-DB',
    description: 'Keyless smart deadbolt lock with touch keypad, auto-locking sensor, & mechanical emergency override key.',
    image_url: stockImage('1558002038-1055907df827'),
    domain_data: {
      itemcode: '10006069',
      material: 'Zinc Alloy (Zamac)',
      finish: 'Matt Black (MB)',
      size: '60/70mm Adjustable Backset',
      pcsperbox: 1,
      warranty: '3 Years Mechanism',
    },
  },
  {
    name: 'Unihopper Glass Magic Box Inner Drawer (600mm / 24")',
    brand: 'Unihopper',
    category: 'Drawer Slides & Systems',
    unit: 'set',
    price: 22500,
    compare_price: 25000,
    cost_price: 15800,
    stock: 16,
    sku: 'UNI-GMB-600',
    description: 'Luxury inner drawer with smoked glass side panels, soft-close runners, & 30kg load capacity.',
    image_url: stockImage('1556911220-e15b29be8c8f'),
    domain_data: {
      itemcode: '100406042-01',
      material: 'Tempered Glass & Aluminum',
      finish: 'Dark Anthracite / Smoked',
      size: '600mm (24") Width',
      pcsperbox: 1,
      warranty: '5 Years Mechanism',
    },
  },
  {
    name: 'Martell Solid Brass Rose Handle Set (Model MH-801)',
    brand: 'Martell',
    category: 'Door Handles & Locks',
    unit: 'set',
    price: 16800,
    compare_price: 19500,
    cost_price: 11900,
    stock: 35,
    sku: 'MTL-MH801-AB',
    description: 'Luxury solid brass door handle pair on rose with heavy 85mm mortise lock body & computer key cylinder.',
    image_url: stockImage('1513694203232-719a280e022f'),
    domain_data: {
      itemcode: 'MH-801-AB',
      material: 'Solid Brass',
      finish: 'Antique Brass (AB)',
      size: '85mm Mortise Backset',
      pcsperbox: 1,
      warranty: '10 Years Finish Guarantee',
    },
    is_featured: true,
  },
  {
    name: 'Anwer Heavy Duty SS 304 Pull Handle 24-Inch (PVD Rose Gold)',
    brand: 'Anwer Architectural',
    category: 'Door Handles & Locks',
    unit: 'pair',
    price: 12500,
    compare_price: 14200,
    cost_price: 8800,
    stock: 25,
    sku: 'ANW-PH24-RG',
    description: 'Back-to-back architectural entrance door pull handle 24" length made from grade 304 stainless steel.',
    image_url: stockImage('1513694203232-719a280e022f'),
    domain_data: {
      itemcode: 'ANW-PH-600RG',
      material: 'Stainless Steel SS 304',
      finish: 'Rose Gold',
      size: '600mm (24") Length',
      gauge: '1.5mm Tube',
      pcsperbox: 1,
      warranty: '10 Years Finish Guarantee',
    },
  },
  {
    name: 'VHID Solid Engineered Teak Wood Flush Door (8ft x 3.5ft)',
    brand: 'VHID',
    category: 'Door Handles & Locks',
    unit: 'pcs',
    price: 45000,
    compare_price: 49500,
    cost_price: 32000,
    stock: 14,
    sku: 'VHID-TEAK-8X35',
    description: 'Solid engineered teak wood main entrance door with acoustic insulation core & moisture-resistant coating.',
    image_url: stockImage('1513694203232-719a280e022f'),
    domain_data: {
      itemcode: 'VHID-D8035',
      material: 'Solid Teak & Engineered Core',
      finish: 'SS Satin / Brushed',
      size: '8ft x 3.5ft (42mm Thick)',
      pcsperbox: 1,
      warranty: '10 Years Finish Guarantee',
    },
  },
  {
    name: 'Hafele Soft-Close Ball Bearing Drawer Slide 18" (450mm)',
    brand: 'Hafele',
    category: 'Drawer Slides & Systems',
    unit: 'pair',
    price: 1850,
    compare_price: 2100,
    cost_price: 1280,
    stock: 120,
    sku: 'HFL-BB-450-SC',
    description: 'Heavy duty 45mm side-mount ball bearing drawer slide with integrated spring soft-closing mechanism.',
    image_url: stockImage('1556911220-e15b29be8c8f'),
    domain_data: {
      itemcode: '494.02.18',
      material: 'Cold Rolled Steel',
      finish: 'Chrome Plated (CP)',
      size: '450mm (18")',
      pcsperbox: 15,
      warranty: '3 Years Mechanism',
    },
  },
  {
    name: 'Crown Heavy Duty 13mm Impact Drill & Tool Kit 750W',
    brand: 'Crown',
    category: 'Power & Hand Tools',
    unit: 'pcs',
    price: 14500,
    compare_price: 16500,
    cost_price: 10200,
    stock: 22,
    sku: 'CRN-ID750-KIT',
    description: 'Professional 750W variable speed impact drill with forward/reverse, chuck key, depth gauge, & 50-piece accessory kit.',
    image_url: stockImage('1504148455328-c376907d081c'),
    domain_data: {
      itemcode: 'CT10030',
      material: 'ABS Plastic & Aluminum',
      finish: 'SS Satin / Brushed',
      size: '13mm Keyed Chuck',
      pcsperbox: 1,
      warranty: '1 Year Mechanism',
    },
  },
  {
    name: 'Yale Heavy Duty Brass Padlock 60mm (Hardened Boron Shackle)',
    brand: 'Yale',
    category: 'Door Handles & Locks',
    unit: 'pcs',
    price: 3850,
    compare_price: 4400,
    cost_price: 2650,
    stock: 45,
    sku: 'YAL-PAD-60MM',
    description: 'Solid brass body padlock with hardened boron steel shackle & dual locking levers for high security protection.',
    image_url: stockImage('1558002038-1055907df827'),
    domain_data: {
      itemcode: 'Y120/60',
      material: 'Solid Brass',
      finish: 'Polished Brass (PB)',
      size: '60mm Body Width',
      pcsperbox: 6,
      warranty: '5 Years Mechanism',
    },
  },
  {
    name: 'Stainless Steel 304 Glass Door Patch Fitting Set',
    brand: 'Anwer Architectural',
    category: 'Glass Door Fittings',
    unit: 'set',
    price: 8900,
    compare_price: 9900,
    cost_price: 6100,
    stock: 30,
    sku: 'ANW-PF-SET-SSS',
    description: 'Top & bottom patch fitting set with pivot pin & floor spring connector for 10-12mm toughened glass doors.',
    image_url: stockImage('1513694203232-719a280e022f'),
    domain_data: {
      itemcode: 'ANW-PF-1012',
      material: 'Stainless Steel SS 304',
      finish: 'SS Satin / Brushed',
      size: 'For 10-12mm Glass',
      pcsperbox: 1,
      warranty: '5 Years Mechanism',
    },
  },
  {
    name: 'Luxury Brass Towel Rack 24" with Robe Hooks',
    brand: 'Anwer Architectural',
    category: 'Bathroom Hardware',
    unit: 'pcs',
    price: 6800,
    compare_price: 7800,
    cost_price: 4600,
    stock: 35,
    sku: 'ANW-TR24-CP',
    description: 'Wall-mounted folding brass towel shelf with lower bar and 4 robe hooks in mirror chrome finish.',
    image_url: stockImage('1584622650111-993a426fbf0a'),
    domain_data: {
      itemcode: 'ANW-TR-600CP',
      material: 'Solid Brass',
      finish: 'Chrome Plated (CP)',
      size: '600mm (24")',
      pcsperbox: 1,
      warranty: '10 Years Finish Guarantee',
    },
  },
]);
