/**
 * Pakistani Lubricants, Engine Oils & Filters Seed Catalog
 * Covers top brand lines: Shell, Caltex, TotalEnergies, ZIC (SK), PSO, Kixx, Castrol, Mobil
 * Plus top filter lines: Guard Filters, Leppon Filters, Vic Filters, Suzuki / Toyota Genuine
 */

export const LUBRICANT_DISTRIBUTION_SEED_PRODUCTS = [
  // ── Passenger Car Motor Oils (PCMO) ───────────────────────────────────────
  {
    sku: 'SH-HX7-10W40-4L',
    name: 'Shell Helix HX7 10W-40 Synthetic Technology Motor Oil (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Passenger Car Motor Oils (PCMO)',
    startingStock: 80,
    defaultPrice: 28800,
    cost_price: 24500,
    description: 'Synthetic technology engine oil for passenger cars. Active Cleansing Technology protects against sludge. 4L x 4 bottles per carton.',
    domain_data: {
      brand: 'Shell',
      viscositygrade: '10W-40',
      apispec: 'API SP',
      aceaspec: 'ACEA A3/B4',
      oemapprovals: 'MB 229.3, VW 502.00/505.00',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },
  {
    sku: 'SH-ULT-5W40-4L',
    name: 'Shell Helix Ultra 5W-40 Fully Synthetic Motor Oil (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Passenger Car Motor Oils (PCMO)',
    startingStock: 45,
    defaultPrice: 42000,
    cost_price: 36000,
    description: '100% Fully synthetic motor oil made from natural gas with PurePlus Technology. Premium protection for modern high-performance engines.',
    domain_data: {
      brand: 'Shell',
      viscositygrade: '5W-40',
      apispec: 'API SP',
      aceaspec: 'ACEA A3/B4',
      oemapprovals: 'BMW LL-01, MB 229.5, Porsche A40',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },
  {
    sku: 'HAV-FORM-2050-1L',
    name: 'Caltex Havoline Formula 20W-50 Multigrade Engine Oil (1L x 12 Cartons)',
    unit: 'carton',
    category: 'Passenger Car Motor Oils (PCMO)',
    startingStock: 120,
    defaultPrice: 25200,
    cost_price: 21500,
    description: 'Shear-stable multigrade gasoline engine oil with Deposit Shield technology. Proven thermal stability for local high-temperature operations.',
    domain_data: {
      brand: 'Caltex',
      viscositygrade: '20W-50',
      apispec: 'API SL',
      oemapprovals: 'JASO MA',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '1 Liter',
      cartonpackqty: 12,
    },
  },
  {
    sku: 'HAV-SYN-1040-4L',
    name: 'Caltex Havoline Synthetic Blend 10W-40 (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Passenger Car Motor Oils (PCMO)',
    startingStock: 60,
    defaultPrice: 29500,
    cost_price: 25000,
    description: 'Synthetic Blend engine oil with Deposit Shield technology designed for passenger cars and light commercial vehicles.',
    domain_data: {
      brand: 'Caltex',
      viscositygrade: '10W-40',
      apispec: 'API SN',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },
  {
    sku: 'ZIC-X7-5W30-4L',
    name: 'ZIC X7 5W-30 VHVI Fully Synthetic Motor Oil (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Passenger Car Motor Oils (PCMO)',
    startingStock: 75,
    defaultPrice: 34500,
    cost_price: 29200,
    description: '100% Synthetic engine oil with YUBASE VHVI tech for fuel efficiency and ultimate wear protection.',
    domain_data: {
      brand: 'ZIC (SK)',
      viscositygrade: '5W-30',
      apispec: 'API SP',
      oemapprovals: 'Dexos1 Gen 2',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },
  {
    sku: 'KIX-G1-5W30-4L',
    name: 'Kixx G1 5W-30 Fully Synthetic Engine Oil (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Passenger Car Motor Oils (PCMO)',
    startingStock: 50,
    defaultPrice: 31000,
    cost_price: 26000,
    description: 'Formulated from Synthetic Base Oil technology for modern passenger cars, GDI engines, and hybrids.',
    domain_data: {
      brand: 'Kixx',
      viscositygrade: '5W-30',
      apispec: 'API SP',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },
  {
    sku: 'MOB-1-0W20-4L',
    name: 'Mobil 1 Advanced Fuel Economy 0W-20 Fully Synthetic (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Passenger Car Motor Oils (PCMO)',
    startingStock: 30,
    defaultPrice: 48000,
    cost_price: 41000,
    description: 'Advanced full synthetic engine oil designed to help deliver outstanding engine protection and enhanced fuel economy in modern Japanese & European cars.',
    domain_data: {
      brand: 'Mobil',
      viscositygrade: '0W-20',
      apispec: 'API SP',
      oemapprovals: 'ILSAC GF-6A, GM dexos1 Gen 3',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },
  {
    sku: 'CAS-GTX-2050-4L',
    name: 'Castrol GTX Essential 20W-50 Engine Oil (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Passenger Car Motor Oils (PCMO)',
    startingStock: 65,
    defaultPrice: 24000,
    cost_price: 20500,
    description: 'Double Action formula cleans away old sludge and protects against new sludge formation in severe driving conditions.',
    domain_data: {
      brand: 'Castrol',
      viscositygrade: '20W-50',
      apispec: 'API SL',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },

  // ── Heavy Duty Diesel Oils (HDDO) ─────────────────────────────────────────
  {
    sku: 'DEL-400-1540-4L',
    name: 'Caltex Delo 400 MG 15W-40 Heavy Duty Diesel Oil (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Heavy Duty Diesel Oils (HDDO)',
    startingStock: 50,
    defaultPrice: 31200,
    cost_price: 26800,
    description: 'Premium ISOSYN tech heavy-duty diesel engine oil for trucks, buses, tractors, and heavy machinery.',
    domain_data: {
      brand: 'Caltex',
      viscositygrade: '15W-40',
      apispec: 'API CI-4',
      oemapprovals: 'Cummins CES 20078, Volvo VDS-3',
      applicationtype: 'Heavy Duty Diesel Oil (HDDO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },
  {
    sku: 'RIM-R4X-1540-4L',
    name: 'Shell Rimula R4 X 15W-40 Heavy Duty Diesel Oil (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Heavy Duty Diesel Oils (HDDO)',
    startingStock: 65,
    defaultPrice: 30800,
    cost_price: 26200,
    description: 'Triple Action protection against wear, deposits, and heat in heavy-duty commercial diesel engines.',
    domain_data: {
      brand: 'Shell',
      viscositygrade: '15W-40',
      apispec: 'API CI-4',
      oemapprovals: 'Mack EO-M+, MAN M3275-1',
      applicationtype: 'Heavy Duty Diesel Oil (HDDO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },
  {
    sku: 'PSO-DEO-2050-4L',
    name: 'PSO Deo 100 20W-50 Heavy Duty Engine Oil (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Heavy Duty Diesel Oils (HDDO)',
    startingStock: 90,
    defaultPrice: 22400,
    cost_price: 18900,
    description: 'Reliable multi-grade heavy duty engine oil formulated for local transport fleets and commercial vehicles.',
    domain_data: {
      brand: 'PSO',
      viscositygrade: '20W-50',
      apispec: 'API CF-4',
      applicationtype: 'Heavy Duty Diesel Oil (HDDO)',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },

  // ── Motorcycle Oils & Small Packs ────────────────────────────────────────
  {
    sku: 'SH-ADV-AX7-1L',
    name: 'Shell Advance AX7 4T 10W-40 Synthetic Technology (1L x 12 Cartons)',
    unit: 'carton',
    category: 'Motorcycle Oils (4T / 2T)',
    startingStock: 110,
    defaultPrice: 21600,
    cost_price: 18200,
    description: 'Synthetic technology 4-stroke motorcycle oil with RCE technology for noise reduction and smooth power.',
    domain_data: {
      brand: 'Shell',
      viscositygrade: '10W-40',
      apispec: 'API SM',
      oemapprovals: 'JASO MA2',
      applicationtype: 'Motorcycle 4T',
      packsize: '1 Liter',
      cartonpackqty: 12,
    },
  },
  {
    sku: 'ZIC-M7-2050-1L',
    name: 'ZIC M7 4T 20W-50 Synthetic Motorcycle Oil (1L x 12 Cartons)',
    unit: 'carton',
    category: 'Motorcycle Oils (4T / 2T)',
    startingStock: 150,
    defaultPrice: 19800,
    cost_price: 16500,
    description: '4-Stroke motorcycle engine oil engineered for smooth clutch engagement and thermal resistance in heavy traffic.',
    domain_data: {
      brand: 'ZIC (SK)',
      viscositygrade: '20W-50',
      apispec: 'API SL',
      oemapprovals: 'JASO MA2',
      applicationtype: 'Motorcycle 4T',
      packsize: '1 Liter',
      cartonpackqty: 12,
    },
  },
  {
    sku: 'HAV-4T-2050-07L',
    name: 'Caltex Havoline 4T 20W-50 Motorcycle Oil (0.7L x 24 Cartons)',
    unit: 'carton',
    category: 'Motorcycle Oils (4T / 2T)',
    startingStock: 140,
    defaultPrice: 28800,
    cost_price: 24200,
    description: '4-Stroke motorcycle engine oil optimized for 70cc / 100cc local commuter motorcycles. 0.7L x 24 bottles per carton.',
    domain_data: {
      brand: 'Caltex',
      viscositygrade: '20W-50',
      apispec: 'API SF',
      oemapprovals: 'JASO MA',
      applicationtype: 'Motorcycle 4T',
      packsize: '500 ml',
      cartonpackqty: 24,
    },
  },

  // ── Oil, Air & Fuel Filters (Pakistani Fleet) ──────────────────────────────
  {
    sku: 'GRD-GFO-101',
    name: 'Guard Oil Filter GFO-101 for Toyota Corolla / Yaris (Box of 24)',
    unit: 'carton',
    category: 'Oil Filters (Guard / Leppon / Vic / Genuine)',
    startingStock: 60,
    defaultPrice: 14400,
    cost_price: 11500,
    description: 'OEM grade oil filter for Toyota Corolla 1.3L / 1.6L / Altis / Yaris. Superior micro-filtration paper protects against engine wear.',
    domain_data: {
      brand: 'Local / Private Label',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '1 Unit',
      cartonpackqty: 24,
    },
  },
  {
    sku: 'GRD-GFA-805',
    name: 'Guard Air Filter GFA-805 for Toyota Corolla GLi / Altis (Box of 10)',
    unit: 'carton',
    category: 'Air Filters (Guard / Leppon / Vic)',
    startingStock: 40,
    defaultPrice: 9500,
    cost_price: 7600,
    description: 'High dust holding capacity air filter element for Toyota Corolla 2008-2024 models.',
    domain_data: {
      brand: 'Local / Private Label',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '1 Unit',
      cartonpackqty: 10,
    },
  },
  {
    sku: 'VIC-C110',
    name: 'Vic Genuine Oil Filter C-110 (Box of 20)',
    unit: 'carton',
    category: 'Oil Filters (Guard / Leppon / Vic / Genuine)',
    startingStock: 35,
    defaultPrice: 22000,
    cost_price: 18000,
    description: 'Made in Japan Vic C-110 premium spin-on oil filter for Toyota Vitz / Passo / Corolla / Allion.',
    domain_data: {
      brand: 'Local / Private Label',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '1 Unit',
      cartonpackqty: 20,
    },
  },
  {
    sku: 'VIC-C932',
    name: 'Vic Oil Filter C-932 for Honda Civic / City (Box of 20)',
    unit: 'carton',
    category: 'Oil Filters (Guard / Leppon / Vic / Genuine)',
    startingStock: 30,
    defaultPrice: 21000,
    cost_price: 17200,
    description: 'Made in Japan Vic C-932 oil filter for Honda Civic 1.8L / Oriel / Turbo / City 1.3L-1.5L / BR-V.',
    domain_data: {
      brand: 'Local / Private Label',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '1 Unit',
      cartonpackqty: 20,
    },
  },
  {
    sku: 'LEP-LFO-202',
    name: 'Leppon Oil Filter LFO-202 for Suzuki Alto / Cultus / Wagon R (Box of 30)',
    unit: 'carton',
    category: 'Oil Filters (Guard / Leppon / Vic / Genuine)',
    startingStock: 80,
    defaultPrice: 13500,
    cost_price: 10800,
    description: 'High-flow oil filter specifically engineered for Suzuki 660cc and 1000cc K10B engine models.',
    domain_data: {
      brand: 'Local / Private Label',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '1 Unit',
      cartonpackqty: 30,
    },
  },
  {
    sku: 'LEP-LFA-401',
    name: 'Leppon Air Filter LFA-401 for Suzuki Wagon R / Cultus (Box of 15)',
    unit: 'carton',
    category: 'Air Filters (Guard / Leppon / Vic)',
    startingStock: 45,
    defaultPrice: 11250,
    cost_price: 8800,
    description: 'Precision molded poly-urethane air filter for Suzuki Wagon R and Cultus VXR/VXL.',
    domain_data: {
      brand: 'Local / Private Label',
      applicationtype: 'Passenger Car Oil (PCO)',
      packsize: '1 Unit',
      cartonpackqty: 15,
    },
  },
  {
    sku: 'GRD-GFF-305',
    name: 'Guard Fuel Filter GFF-305 for Toyota Hilux Revo / Fortuner Diesel (Box of 12)',
    unit: 'carton',
    category: 'Fuel & Diesel Filters (Guard / Leppon)',
    startingStock: 25,
    defaultPrice: 18000,
    cost_price: 14500,
    description: 'Heavy duty diesel fuel filter with water separator media for 1KD-FTV / 1GD-FTV engines.',
    domain_data: {
      brand: 'Local / Private Label',
      applicationtype: 'Heavy Duty Diesel Oil (HDDO)',
      packsize: '1 Unit',
      cartonpackqty: 12,
    },
  },

  // ── Industrial & Hydraulics ────────────────────────────────────────────────
  {
    sku: 'SH-TEL-MX46-208L',
    name: 'Shell Tellus S2 MX 46 Industrial Hydraulic Oil (208L Drum)',
    unit: 'drum',
    category: 'Industrial Lubricants & Hydraulics',
    startingStock: 12,
    defaultPrice: 185000,
    cost_price: 158000,
    description: 'High performance zinc-based hydraulic fluid for industrial manufacturing plants and construction machinery.',
    domain_data: {
      brand: 'Shell',
      viscositygrade: 'SAE 40',
      apispec: 'ISO VG 46',
      oemapprovals: 'Eaton E-FDGN-TB002-E, Parker Denison HF-0',
      applicationtype: 'Hydraulic Oil',
      packsize: '208 Liter Drum',
      cartonpackqty: 1,
    },
  },
  {
    sku: 'CAL-RAN-HD68-208L',
    name: 'Caltex Rando HD 68 Hydraulic Oil (208L Drum)',
    unit: 'drum',
    category: 'Industrial Lubricants & Hydraulics',
    startingStock: 10,
    defaultPrice: 178000,
    cost_price: 152000,
    description: 'Premium anti-wear hydraulic oil for high-pressure industrial systems and earthmoving equipment.',
    domain_data: {
      brand: 'Caltex',
      viscositygrade: 'SAE 50',
      apispec: 'ISO VG 68',
      applicationtype: 'Hydraulic Oil',
      packsize: '208 Liter Drum',
      cartonpackqty: 1,
    },
  },

  // ── Gear Oils, Transmission & Coolants ───────────────────────────────────
  {
    sku: 'TOT-TRN-7590-1L',
    name: 'Total Transmission Dual 9 FE 75W-90 Synthetic Gear Oil (1L x 12 Cartons)',
    unit: 'carton',
    category: 'Gear Oils & Transmission Fluids',
    startingStock: 40,
    defaultPrice: 33600,
    cost_price: 28500,
    description: 'High-performance synthetic gear oil for manual transmissions and rear axles requiring API GL-4 / GL-5.',
    domain_data: {
      brand: 'TotalEnergies',
      viscositygrade: '80W-90',
      apispec: 'API GL-5',
      applicationtype: 'Gear Oil',
      packsize: '1 Liter',
      cartonpackqty: 12,
    },
  },
  {
    sku: 'HAV-COOL-OAT-4L',
    name: 'Caltex Havoline Extended Life Radiator Coolant Premixed (4L x 4 Cartons)',
    unit: 'carton',
    category: 'Coolants & Specialty Fluids',
    startingStock: 65,
    defaultPrice: 19200,
    cost_price: 16000,
    description: 'Long-life organic additive technology (OAT) radiator coolant for anti-boil and anti-freeze protection.',
    domain_data: {
      brand: 'Caltex',
      applicationtype: 'Coolant / Radiator',
      packsize: '4 Liter',
      cartonpackqty: 4,
    },
  },
];
