/**
 * Construction & Infrastructure Contracting Domain Knowledge Base
 * Public and Private Sector Construction Management (Pakistan & Global 2026 Standards)
 *
 * Covers:
 * - PEC Licensing Categories (C-A to C-6) & Codes (CE01, CE02, BC01, etc.)
 * - Bidding & Procurement (PPRA / SPPRA / KPPRA / BPPRA / EPADS)
 * - Schedule of Rates (Punjab MRS, Federal CSR, SPPRA DRC, KP CSR)
 * - BOQ Estimation & IPC (Interim Payment Certificate) Running Bills
 * - Mobilization Advance (10-15%), Retention Money (5-10%), Price Escalation (PEC Clause 70)
 * - FBR WHT Section 153(1)(c) & Provincial Tax Authorities (PRA, SRB, KPRA, BRA)
 * - 2026 Material Benchmark Rates & Plant Machinery Rental Benchmarks
 */

export const constructionDomains = {
  'construction-contractor': {
    name: 'Construction & Infrastructure Contracting',
    name_ur: 'تعمیرات و انفراسٹرکچر کانٹریکٹنگ',
    icon: 'HardHat',
    description:
      'Public & private sector construction management for buildings, highways, bridges, dams & EPC projects. BOQ billing, IPC running bills, MRS/CSR schedule rates, material rate intelligence, labor tracking, plant & machinery logs, mobilization advance, retention, and FIDIC/PEC compliance.',
    units: [
      'Cu.M',
      'Cu.Ft',
      'Ton',
      'R.Ft',
      'Sq.Ft',
      'Kg',
      'Bag',
      'Trip',
      'Hour',
      'Day',
      'Job',
      'Month',
      'Sqr',
    ],
    taxCategories: [
      'FBR WHT Sec 153(1)(c) - Civil Works (7.5%)',
      'FBR WHT Sec 153(1)(c) - Non-Company (8%)',
      'PRA Construction Services (5% Reduced)',
      'PRA Standard Construction (16%)',
      'SRB Construction Services (13%)',
      'KPRA Construction Services (15%)',
      'BRA Construction Services (15%)',
      'WHT Exempt / Tax Certificate',
    ],
    defaultTax: 7.5,
    defaultHSN: '9954', // Construction services SAC / HS Code
    pakistaniFeatures: {
      paymentGateways: ['bank_transfer', 'cheque', 'pay_order', 'letter_of_credit', 'treasury_bill', 'cod'],
      taxCompliance: [
        'fbr',
        'pec',
        'ppra',
        'pra',
        'srb',
        'kpra',
        'bra',
        'ntn',
        'wht_sec_153',
        'e_invoicing_zatca_compatible',
      ],
      languages: ['en', 'ur'],
      regulators: [
        'Pakistan Engineering Council (PEC)',
        'PPRA (Federal / Punjab / Sindh / KP / Balochistan)',
        'NHA (National Highway Authority)',
        'CWD (Communication & Works Dept)',
        'MDA / LDA / KDA Development Authorities',
        'FBR / Provincial Revenue Authorities',
      ],
      contractorCategories: [
        'C-A (No Limit)',
        'C-B (Up to PKR 3,000M)',
        'C-1 (Up to PKR 1,000M)',
        'C-2 (Up to PKR 500M)',
        'C-3 (Up to PKR 250M)',
        'C-4 (Up to PKR 100M)',
        'C-5 (Up to PKR 50M)',
        'C-6 (Up to PKR 25M)',
      ],
      specializations: [
        'CE01 - Roads & Highways',
        'CE02 - Bridges & Structures',
        'CE04 - Irrigation & Dams',
        'CE09 - Sewerage & Water Supply',
        'BC01 - Building Construction',
        'EE01 - High Voltage & Substation',
        'ME01 - HVAC & Heavy Machinery',
      ],
      scheduleOfRates: [
        'Punjab Market Rate System (MRS / CSR)',
        'Federal Composite Schedule of Rates (NHA CSR)',
        'Sindh SPPRA DRC / Schedule Rates',
        'KPK Composite Schedule of Rates (CSR)',
        'Balochistan Schedule of Rates (BSR)',
      ],
      contractClauses: [
        'Interim Payment Certificate (IPC)',
        'Mobilization Advance (10-15%)',
        'Retention Money (5-10%)',
        'Performance Security Guarantee (5-10%)',
        'Escalation / Price Adjustment (PEC Clause 70)',
        'Secured Advance on Site Materials',
        'Defects Liability Period (DLP 12-24 mos)',
      ],
      popularBrands: [
        'Mughal Steel',
        'Amreli Steels',
        'Ittehad Steel',
        'FF Steel',
        'Bestway Cement',
        'Maple Leaf Cement',
        'Lucky Cement',
        'Cherat Cement',
        'DG Khan Cement',
        'Attock Petroleum',
        'National Refinery',
        'Caterpillar',
        'Komatsu',
        'JCB',
        'Foton',
        'Millat Tractors',
      ],
      materialBenchmarkRatesPKR: {
        'Deformed Steel Rebar (Grade 60)': { rate: 260000, unit: 'Ton' },
        'Ordinary Portland Cement (OPC 50kg Bag)': { rate: 1420, unit: 'Bag' },
        'Bitumen Grade 60/70': { rate: 210000, unit: 'Ton' },
        'Ready-Mix Concrete (C25 / 3000 PSI)': { rate: 15500, unit: 'Cu.M' },
        'Ready-Mix Concrete (C30 / 4000 PSI)': { rate: 17500, unit: 'Cu.M' },
        'Crushed Aggregate (Margalla 19mm)': { rate: 120, unit: 'Cu.Ft' },
        'Sand (Lawrencepur / Chenab)': { rate: 55, unit: 'Cu.Ft' },
        'Earthwork Excavation & Compaction': { rate: 600, unit: 'Cu.M' },
        'Skilled Steel Fixer / Mason Labor': { rate: 3000, unit: 'Day' },
        'Unskilled Helper Labor': { rate: 1750, unit: 'Day' },
      },
      machineryRentalRatesPKR: {
        'Excavator (CAT 320 / Komatsu PC200)': { rate: 14000, unit: 'Hour' },
        'Motor Grader (CAT 140K)': { rate: 16000, unit: 'Hour' },
        'Vibratory Road Roller (10-12 Ton)': { rate: 8500, unit: 'Hour' },
        'Asphalt Paver (Vögele / Dynapac)': { rate: 30000, unit: 'Hour' },
        'Concrete Transit Mixer Truck (6-8 Cu.M)': { rate: 95000, unit: 'Day' },
      },
    },
    productFields: [
      'boq_item_no',
      'specification_grade',
      'unit_rate',
      'schedule_code',
      'material_cost_ratio',
      'labor_cost_ratio',
      'machinery_cost_ratio',
      'station_location',
    ],
    customerFields: [
      'client_type',
      'pec_project_no',
      'employer_dept',
      'sanctioned_amount',
      'retention_rate',
      'mobilization_rate',
    ],
    vendorFields: [
      'subcontractor_category',
      'pec_license_no',
      'specialization_code',
      'tax_exemption_status',
      'retainage_rate',
    ],
    inventoryFeatures: [
      'boq_tracking',
      'ipc_billing',
      'machinery_logbook',
      'subcontractor_ledger',
      'price_escalation_clause',
      'mobilization_advance_recovery',
      'retention_money_ledger',
      'site_material_requisition',
      'batch_tracking',
    ],
    batchTrackingEnabled: true,
    serialTrackingEnabled: true,
    manufacturingEnabled: true,
    multiLocationEnabled: true,
    reports: [
      'BOQ Cost & Variance Summary',
      'IPC Running Bill History & Retention Ledger',
      'Material Consumption vs BOQ Estimate Analysis',
      'Machinery Fuel & Hour-Meter Log',
      'Subcontractor Running Account & Retainage Report',
      'PEC Price Adjustment & Escalation Index Statement',
    ],
    intelligence: {
      seasonality: 'medium',
      perishability: 'low',
      shelfLife: 180,
      demandVolatility: 0.3,
      minOrderQuantity: 1,
      leadTime: 7,
      costIndices: {
        steelWPI: 1.15,
        cementWPI: 1.10,
        bitumenWPI: 1.20,
        laborWPI: 1.08,
        fuelWPI: 1.18,
      },
    },
    setupTemplate: {
      categories: [
        'Civil & Structural',
        'Roads & Asphalt',
        'Earthwork & Compaction',
        'MEP & Electrical',
        'Plant & Heavy Equipment',
        'Subcontractor Labor',
      ],
      suggestedProducts: [
        {
          name: 'Deformed Steel Rebar Grade 60 (12mm - 25mm)',
          category: 'Civil & Structural',
          sku: 'CONST-STEEL-G60',
          unit: 'Ton',
          price: 260000,
          cost_price: 245000,
          stock: 120,
          min_stock: 25,
          domain_data: {
            boq_item_no: 'BOQ-3.1',
            specification_grade: 'ASTM A615 Grade 60',
            schedule_code: 'MRS-PUNJAB-14.2',
            material_cost_ratio: '0.90',
            station_location: 'Central Batching Yard & Site Storage',
          },
        },
        {
          name: 'Ordinary Portland Cement OPC 50kg Bags',
          category: 'Civil & Structural',
          sku: 'CONST-CEMENT-OPC',
          unit: 'Bag',
          price: 1420,
          cost_price: 1350,
          stock: 2500,
          min_stock: 500,
          domain_data: {
            boq_item_no: 'BOQ-3.2',
            specification_grade: 'PSQCA / BS EN 197-1 CEM I 42.5N',
            schedule_code: 'MRS-PUNJAB-6.1',
            material_cost_ratio: '0.95',
            station_location: 'Main Warehouse Shed',
          },
        },
        {
          name: 'Ready-Mix Concrete C25 (3000 PSI @ 28 Days)',
          category: 'Civil & Structural',
          sku: 'CONST-RMC-C25',
          unit: 'Cu.M',
          price: 15500,
          cost_price: 14000,
          stock: 450,
          min_stock: 50,
          domain_data: {
            boq_item_no: 'BOQ-3.5',
            specification_grade: 'Class B Concrete 1:2:4 Mix',
            schedule_code: 'MRS-PUNJAB-6.12',
            material_cost_ratio: '0.70',
            labor_cost_ratio: '0.20',
            station_location: 'Structure Pier P-01 to P-04',
          },
        },
        {
          name: 'Bitumen Asphalt Binder Grade 60/70',
          category: 'Roads & Asphalt',
          sku: 'CONST-BITUMEN-6070',
          unit: 'Ton',
          price: 210000,
          cost_price: 198000,
          stock: 80,
          min_stock: 15,
          domain_data: {
            boq_item_no: 'BOQ-4.2',
            specification_grade: 'AASHTO M20 Penetration 60/70',
            schedule_code: 'CSR-NHA-401B',
            material_cost_ratio: '0.85',
            station_location: 'Asphalt Plant Site Base',
          },
        },
        {
          name: 'Crushed Stone Aggregate 19mm (Margalla / Sargodha)',
          category: 'Roads & Asphalt',
          sku: 'CONST-AGG-19MM',
          unit: 'Cu.Ft',
          price: 120,
          cost_price: 105,
          stock: 15000,
          min_stock: 3000,
          domain_data: {
            boq_item_no: 'BOQ-4.1',
            specification_grade: 'Sub-base & Aggregate Base Course Grade A',
            schedule_code: 'MRS-PUNJAB-4.3',
            material_cost_ratio: '0.80',
            station_location: 'KM 14+200 Stockpile Yard',
          },
        },
        {
          name: 'Earthwork Excavation & Sub-grade Compaction',
          category: 'Earthwork & Compaction',
          sku: 'CONST-EARTH-EXC',
          unit: 'Cu.M',
          price: 600,
          cost_price: 480,
          stock: 25000,
          min_stock: 1000,
          domain_data: {
            boq_item_no: 'BOQ-1.1',
            specification_grade: '95% Modified AASHTO Compaction',
            schedule_code: 'MRS-PUNJAB-3.1',
            machinery_cost_ratio: '0.60',
            labor_cost_ratio: '0.25',
            station_location: 'Embankment Cut & Fill Reach-1',
          },
        },
        {
          name: 'Excavator Hydraulic (CAT 320 / Komatsu PC200 Log)',
          category: 'Plant & Heavy Equipment',
          sku: 'CONST-EQ-EXC320',
          unit: 'Hour',
          price: 14000,
          cost_price: 11000,
          stock: 1200,
          min_stock: 100,
          domain_data: {
            boq_item_no: 'EQ-01',
            specification_grade: '1.0 Cu.M Bucket Capacity Hydraulic Heavy Duty',
            schedule_code: 'CSR-MACH-01',
            machinery_cost_ratio: '0.90',
            station_location: 'Heavy Machinery Fleet Pool',
          },
        },
        {
          name: 'Steel Fixer & Shuttering Subcontractor Gang Log',
          category: 'Subcontractor Labor',
          sku: 'CONST-LABOR-GANG',
          unit: 'Day',
          price: 3000,
          cost_price: 2500,
          stock: 350,
          min_stock: 50,
          domain_data: {
            boq_item_no: 'LAB-02',
            specification_grade: 'Skilled Structural Reinforcement Crew',
            schedule_code: 'MRS-LABOR-SKILLED',
            labor_cost_ratio: '0.95',
            station_location: 'Tower Slab Casting Deck',
          },
        },
      ],
    },
  },
};
