export const lubricantDomains = {
    'lubricant-distribution': {
        name: 'Lubricant & Engine Oil Distribution',
        icon: 'Droplet',
        imageUrl: '/industrial_hero_image.png',
        productFields: [
            'Brand',
            'Viscosity Grade',
            'API Spec',
            'ACEA Spec',
            'OEM Approvals',
            'Application Type',
            'Pack Size',
            'Carton Pack Qty',
        ],
        taxCategories: ['Sales Tax 18%', 'Sales Tax 18% + 3% Further Tax', 'Exempt'],
        units: ['carton', 'bottle', 'litre', 'drum', 'can'],
        alternateUnits: { carton: 'bottle', drum: 'litre' },
        defaultTax: 18,
        fieldConfig: {
            brand: {
                label: 'Brand / Principal',
                type: 'select',
                options: [
                    'Shell',
                    'Caltex',
                    'TotalEnergies',
                    'ZIC (SK)',
                    'PSO',
                    'Kixx',
                    'Mobil',
                    'Castrol',
                    'Local / Private Label',
                ],
                required: true,
            },
            viscositygrade: {
                label: 'Viscosity Grade',
                type: 'select',
                options: [
                    '0W-20',
                    '5W-30',
                    '5W-40',
                    '10W-30',
                    '10W-40',
                    '15W-40',
                    '20W-50',
                    'SAE 40',
                    'SAE 50',
                    '80W-90',
                    '85W-140',
                ],
                required: true,
            },
            apispec: {
                label: 'API Specification',
                type: 'select',
                options: [
                    'API SP',
                    'API SN Plus',
                    'API SN',
                    'API SL',
                    'API CK-4',
                    'API CJ-4',
                    'API CI-4',
                    'API GL-4',
                    'API GL-5',
                ],
                required: false,
            },
            aceaspec: {
                label: 'ACEA Specification',
                type: 'text',
                placeholder: 'e.g. ACEA A3/B4, C3, E7',
                required: false,
            },
            oemapprovals: {
                label: 'OEM Approvals',
                type: 'text',
                placeholder: 'e.g. MB 229.5, VW 502.00, BMW LL-01',
                required: false,
            },
            applicationtype: {
                label: 'Application Type',
                type: 'select',
                options: [
                    'Passenger Car Oil (PCO)',
                    'Heavy Duty Diesel Oil (HDDO)',
                    'Motorcycle 4T',
                    'Motorcycle 2T',
                    'Industrial Lubricant',
                    'Hydraulic Oil',
                    'Gear Oil',
                    'ATF / Transmission',
                    'Grease',
                    'Coolant / Radiator',
                    'Brake Fluid',
                ],
                required: true,
            },
            packsize: {
                label: 'Pack Size',
                type: 'select',
                options: [
                    '200 ml',
                    '500 ml',
                    '1 Liter',
                    '1.5 Liter',
                    '3 Liter',
                    '4 Liter',
                    '5 Liter',
                    '10 Liter',
                    '20 Liter',
                    '208 Liter Drum',
                ],
                required: true,
            },
            cartonpackqty: {
                label: 'Bottles / Units per Carton',
                type: 'number',
                placeholder: 'e.g. 12, 24, 4, 1',
                required: true,
            },
        },
        customerFields: [
            'Customer Type',
            'Territory / Route',
            'CNIC / NTN',
            'STRN Number',
            'Credit Limit (PKR)',
            'Assigned Salesman',
        ],
        vendorFields: [
            'Principal Agreement',
            'Territory Rights',
            'Distributor Margin %',
            'NTN / STRN',
            'Credit Limit (PKR)',
        ],
        inventoryFeatures: [
            'Multi-Unit Unit Conversion (Carton -> Bottle -> Liter)',
            'Van Stock & Mobile Reconciliation',
            'Batch & Expiry Tracking',
            'Territory & Beat Route Management',
            'Credit Limit Enforcement & Aging',
            'Principal Targets & Scheme Rebates',
            'Pakistani Tax Invoicing (GST + Further Tax)',
            'Cheque & PDC Tracking',
        ],
        reports: [
            {
                id: 'van_stock_reconciliation',
                name: 'Van Stock Reconciliation Report',
                description: 'Daily mobile van inventory loading, doorstep sales, customer returns, and physical variance audit.',
            },
            {
                id: 'customer_aging_udhaar',
                name: 'Customer Udhaar & Aging Report',
                description: 'Accounts receivable ledger broken down by aging buckets (Current, 1-30, 31-60, 61-90, 90+ days) and credit holds.',
            },
            {
                id: 'salesman_beat_route',
                name: 'Salesman Beat Route Performance',
                description: 'Salesman daily visits, order volume, no-order reasons, collections, and target completion %.',
            },
            {
                id: 'principal_target_claims',
                name: 'Principal Target vs Achievement & Claims',
                description: 'Oil company sales targets (Shell, Caltex, ZIC, PSO), volume scheme rebates, and pending claim settlements.',
            },
            {
                id: 'brand_territory_profitability',
                name: 'Brand & Territory Profitability',
                description: 'Net contribution analysis by oil brand, pack size, geographic territory, beat route, and customer category.',
            },
            {
                id: 'reorder_deadstock_intelligence',
                name: 'Reorder & Dead-Stock Intelligence',
                description: 'Stock coverage (months of inventory), fast-mover stockout alerts, and overstock risk analysis.',
            },
        ],
        paymentTerms: ['Cash', 'Credit 7 Days', 'Credit 15 Days', 'Credit 30 Days', 'PDC Cheque'],
        stockValuationMethod: 'FIFO',
        reorderEnabled: true,
        multiLocationEnabled: true,
        serialTrackingEnabled: false,
        batchTrackingEnabled: true,
        expiryTrackingEnabled: true,
        manufacturingEnabled: false,
        intelligence: {
            seasonality: 'medium',
            peakMonths: ['May', 'June', 'July', 'October'],
            perishability: 'low',
            shelfLife: 1825, // 5 years
            demandVolatility: 0.3,
            minOrderQuantity: 5, // cartons
            leadTime: 7,
        },
        setupTemplate: {
            categories: [
                'Passenger Car Motor Oils (PCMO)',
                'Heavy Duty Diesel Oils (HDDO)',
                'Motorcycle Oils (4T / 2T)',
                'Industrial Lubricants & Hydraulics',
                'Gear Oils & Transmission Fluids',
                'Coolants & Specialty Fluids',
            ],
            suggestedProducts: [
                {
                    name: 'Shell Helix HX7 10W-40 Synthetic Technology (4L Carton x 4)',
                    unit: 'carton',
                    category: 'Passenger Car Motor Oils (PCMO)',
                    startingStock: 50,
                    defaultPrice: 28500,
                    description: 'Synthetic technology motor oil for gasoline and diesel engines. 4L x 4 bottles per carton.',
                },
                {
                    name: 'Caltex Havoline Formula 20W-50 (1L Carton x 12)',
                    unit: 'carton',
                    category: 'Passenger Car Motor Oils (PCMO)',
                    startingStock: 100,
                    defaultPrice: 24600,
                    description: 'High quality multigrade engine oil for passenger cars. 1L x 12 bottles per carton.',
                },
                {
                    name: 'ZIC X7 5W-30 Fully Synthetic (4L Carton x 4)',
                    unit: 'carton',
                    category: 'Passenger Car Motor Oils (PCMO)',
                    startingStock: 40,
                    defaultPrice: 34000,
                    description: '100% Fully Synthetic motor oil with VHVI technology. 4L x 4 bottles per carton.',
                },
                {
                    name: 'PSO Carient Fully Synthetic 5W-30 (4L Carton x 4)',
                    unit: 'carton',
                    category: 'Passenger Car Motor Oils (PCMO)',
                    startingStock: 60,
                    defaultPrice: 26000,
                    description: 'Premium fully synthetic engine oil for modern gasoline engines. 4L x 4 bottles per carton.',
                },
                {
                    name: 'Total Quartz 9000 5W-40 (4L Carton x 4)',
                    unit: 'carton',
                    category: 'Passenger Car Motor Oils (PCMO)',
                    startingStock: 35,
                    defaultPrice: 32000,
                    description: 'Advanced synthetic technology engine oil. 4L x 4 bottles per carton.',
                },
            ],
        },
    },
};
